FROM ghcr.io/inti-cmnb/base_os:latest_nightly
LABEL Maintainer="Salvador E. Tropea <stropea@inti.gob.ar>"
LABEL Description="KiCad 9 on Debian + base tools"
LABEL org.opencontainers.image.description="KiCad 9 on Debian + base tools"

# Using kicad/kicad KiCad is already installed
COPY kicad_version.py /usr/bin/
