name: Erase old versions

on:
  push:
    tags:
      - clean_*
  repository_dispatch:
    types: [clean]

jobs:
  do_clean:
    name: Remove old versions
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Remove old untagged and dev_* versions
      run: |
        cd tools
        python3 garbage_collector.py ${{ secrets.PKG_TOKEN }}
