name: Docker Hub upload (KiCad 6)

on:
  push:
    tags:
      - ki6_*
  repository_dispatch:
    types: [build_k6]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Copy download script
      run: |
        cp dl_deb.py ki6/

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          setsoft/kicad_debian
          ghcr.io/${{ github.repository }}
        tags: |
          type=raw,ki6

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ki6
        push: true
        tags: |
          setsoft/kicad_debian:ki6
          ghcr.io/inti-cmnb/kicad_debian:ki6
          ghcr.io/inti-cmnb/kicad6_debian:latest
        labels: ${{ steps.meta.outputs.labels }}

    - name: Trigger KiCad-Auto image build
      run: |
        curl -X POST -u "${{secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/INTI-CMNB/kicad_auto/dispatches --data '{"event_type": "build_k6"}'
